shortlink_manager.utm_parameter_definition_type.*:
  type: config_entity
  label: 'UTM Parameter Definition type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
